name = "G.I.M.P.S Create"
author = "Cooks Corner"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b60dfa3bf0beb746b859a160812f5fe0d13937337fc8f9dd43fc3f79af2ab38e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
