name = "G.I.M.P.S Create"
author = "Cooks Corner"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beae31355c4be2afeadffbe5fddb4838b04b157cd55705c2ea98305095697b89"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.243"
